PLUGIN_WASM_COMPONENT := 1
PLUGIN_WIT_WORLD := automap-plugin
PLUGIN_COMPONENT_NAME := automap_plugin
PLUGIN_COMPONENT_SOURCES := $(PLUGIN_PATH)/component.c
PLUGIN_WIT_PACKAGE := gams:automap@1.0.0.wasm
